server:
  port: 8083

spring:
  application:
    name: ticket-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/htms-ticketservice

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/