server:
  port: 8082

spring:
  application:
    name: vehicle-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/htms-vehicleservice

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/